WITH
 a  AS (SELECT pg_size_pretty(pg_database_size(current_database())) AS db_size)
,b  AS (SELECT COUNT(*) AS db_connections FROM pg_stat_activity WHERE datname = (SELECT current_database()))
,d  AS (SELECT COUNT(*) AS table_count FROM pg_tables WHERE schemaname NOT IN ('pg_catalog', 'information_schema'))
,e  AS (SELECT COUNT(*) AS index_count FROM pg_indexes WHERE schemaname != 'pg_catalog')
,f  AS (SELECT pg_size_pretty(SUM(pg_table_size(c.oid))) AS tables_size FROM pg_class AS c LEFT JOIN pg_namespace AS n ON (n.oid = c.relnamespace) WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND c.relkind IN ('r', 't','f','p') AND nspname != 'pg_toast')
,q  AS (SELECT pg_size_pretty(SUM(pg_total_relation_size(c.oid))) AS indexes_size FROM pg_class AS c LEFT JOIN pg_namespace AS n ON (n.oid = c.relnamespace) WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND c.relkind IN ('r', 't','f','p') AND nspname != 'pg_toast')
,s  AS (SELECT pg_size_pretty(SUM(pg_total_relation_size(c.oid))) AS mviews_size FROM pg_class AS c LEFT JOIN pg_namespace AS n ON (n.oid = c.relnamespace) WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND c.relkind = 'm' AND nspname != 'pg_toast')
,t  AS (SELECT pg_size_pretty(SUM(pg_total_relation_size(c.oid))) AS sequences_size FROM pg_class AS c LEFT JOIN pg_namespace AS n ON (n.oid = c.relnamespace) WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND c.relkind = 's' AND nspname != 'pg_toast')
,g  AS (SELECT CASE WHEN datconnlimit < 0 THEN CAST('unlimited' AS CHAR(9)) WHEN datconnlimit = 0 THEN CAST('closed' AS CHAR(6)) ELSE CAST(datconnlimit AS VARCHAR) END AS max_connections FROM pg_database WHERE datname = (SELECT current_database()))
,h  AS (SELECT COUNT(*) AS extension_count FROM pg_extension)
,i  AS (SELECT COUNT(*) AS schema_count FROM pg_namespace WHERE nspname NOT LIKE 'pg_%' AND nspname != 'information_schema')
,j  AS (SELECT CASE WHEN (SELECT COUNT(*) FROM pg_publication) > 0 OR (SELECT COUNT(*) FROM pg_subscription) > 0 THEN true ELSE false END AS logic_repl_setup)
,k  AS (SELECT COUNT(*) AS publication_count FROM pg_publication)
,l  AS (SELECT COUNT(*) AS subscription_count FROM pg_subscription)
,m  AS (SELECT COUNT(*) AS lock_count FROM pg_locks l LEFT JOIN pg_class c ON l.relation = c.oid WHERE locktype != 'virtualxid' AND c.relname NOT  LIKE 'pg_%')
,n  AS (SELECT COUNT(*) AS mview_count FROM pg_matviews)
,o  AS (SELECT COUNT(*) AS view_count FROM pg_views WHERE schemaname NOT IN ('pg_catalog', 'information_schema'))
,p  AS (SELECT db_connections||'/'||max_connections AS db_connections FROM b,g)
SELECT * FROM a,p,d,e,f,q,s,t,h,i,j,k,l,m,n,o;
