WITH
 b  AS (SELECT pg_size_pretty((setting::int*1024)::bigint) AS work_mem FROM pg_settings WHERE name = 'work_mem')
,c  AS (SELECT setting AS archive_mode FROM pg_settings WHERE name = 'archive_mode')
,d  AS (SELECT setting AS archive_command FROM pg_settings WHERE name = 'archive_command')
,e  AS (SELECT pg_size_pretty((setting::int*1024*1024)::bigint) AS min_wal_size FROM pg_settings WHERE name = 'min_wal_size')
,f  AS (SELECT pg_size_pretty((setting::int*1024*1024)::bigint) AS max_wal_size FROM pg_settings WHERE name = 'max_wal_size')
,g  AS (SELECT setting AS max_connections FROM pg_settings WHERE name = 'max_connections')
,h  AS (SELECT (setting::numeric*100)::smallint||' %' AS checkpoint_completion_target FROM pg_settings WHERE name = 'checkpoint_completion_target')
,i  AS (SELECT setting AS default_statistics_target FROM pg_settings WHERE name = 'default_statistics_target')
,j  AS (SELECT setting AS random_page_cost FROM pg_settings WHERE name = 'random_page_cost')
,k  AS (SELECT pg_size_pretty((setting::int*1024)::bigint) AS maintenance_work_mem FROM pg_settings WHERE name = 'maintenance_work_mem')
,l  AS (SELECT pg_size_pretty((setting::int*1024)::bigint) AS shared_buffers FROM pg_settings WHERE name = 'shared_buffers')
,m  AS (SELECT pg_size_pretty((setting::bigint*(SELECT current_setting('block_size')::bigint))::bigint) AS effective_cache_size FROM pg_settings WHERE name = 'effective_cache_size')
,n  AS (SELECT setting AS effective_io_concurrency FROM pg_settings WHERE name = 'effective_io_concurrency')
,o  AS (SELECT setting AS max_worker_processes FROM pg_settings WHERE name = 'max_worker_processes')
,p  AS (SELECT setting AS max_parallel_workers FROM pg_settings WHERE name = 'max_parallel_workers')
SELECT * FROM b,c,d,e,f,g,h,i,j,k,l,m,n,o,p;
